### ISSUE TITLE
Internet sharing does not turn off

### ISSUE THREAD

**Issue by amolgautam25** [MrL1605/NetworkManager#1]
Tethering  does not turn off.
Although i agree that since data is turned off tethering is useless, but still it will consume a lot of battery.

**Comment by MrL1605** [comment]
Thanks for using Network Manager. :smile: 

Repository description clearly describes that 
**Network Manager turns off data connection (Mobile data, Wifi) at a specific time.** 
It was intended to save data usage in users phone.

Maybe I would take your suggestion into consideration in next update. :octocat:
